New bootstrap script.

diff --git a/_scripts/bootstrap b/_scripts/bootstrap
--- a/_scripts/bootstrap
+++ b/_scripts/bootstrap
@@ -1,148 +1,48 @@
 #!/usr/bin/env bash
 
 SOURCE="${BASH_SOURCE[0]}"
-while [ -h "$SOURCE" ]; do
+while [ -h "$SOURCE" ]; do 
     DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
     SOURCE="$(readlink "$SOURCE")"
-    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
+    [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" 
 done
 DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
 
-ETC_ROOT="${DIR}/../"
-
-set -e
-
-echo ''
-
-find_destination () {
-    local src=$1
-    local dst=
-
-    src=$(basename "$src")
-    src=${src%%.symlink}
-
-    if [[ $src == "bin" ]]; then
-        dst=~/bin
-    elif [[ ${src%%.*} == "config" ]]; then
-        dst=${src##config.}
-        dst="$HOME"/.config/"${dst}"
-    elif [[ ${src%%.*} == "xdg-applications" ]]; then
-        dst=${src##xdg-applications.}
-        mkdir -p ~/.local/share/applications
-        dst="$HOME"/.local/share/applications/"${dst}"
-    else
-        dst="$HOME"/
-        dst="$HOME/.${src%%.symlink}"
-    fi
-
-    echo $dst
-}
+ETC="${DIR}/.."
+ETC=$(realpath "$ETC")
 
 info () {
-  printf "  [ \033[00;34m..\033[0m ] $1"
+    printf "  [ \033[00;34m..\033[0m ] $1"
 }
 
 user () {
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+    printf "\r  [ \033[0;33m?\033[0m ] $1 "
 }
 
 success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
 }
 
 fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+    echo ''
+    exit 1
 }
 
-link_file () {
-  local src=$1 dst=$2
+# main
+if [ "x$1" = "x-f" ] ; then
+    force=true
+else
+    force=false
+fi
 
-  local overwrite= backup= skip=
-  local action=
-
-  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
-  then
-
-    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-    then
-
-      local currentSrc="$(readlink $dst)"
-
-      if [ "$currentSrc" == "$src" ]
-      then
-
-        skip=true;
-
-      else
-
-        user "File already exists: $(basename "$src"), what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
-
-        case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
-        esac
-
-      fi
-
+cd $ETC
+for config in $(ls -d */ | grep -Ev '^_') ; do
+    stow "$config"
+    if [ $? != 0 ] ; then
+        fail "couldn't install $config"
     fi
-
-    overwrite=${overwrite:-$overwrite_all}
-    backup=${backup:-$backup_all}
-    skip=${skip:-$skip_all}
-
-    if [ "$overwrite" == "true" ]
-    then
-      rm -rf "$dst"
-      success "removed $dst"
-    fi
-
-    if [ "$backup" == "true" ]
-    then
-      mv "$dst" "${dst}.backup"
-      success "moved $dst to ${dst}.backup"
-    fi
-
-    if [ "$skip" == "true" ]
-    then
-      success "skipped $src"
-    fi
-  fi
-
-  if [ "$skip" != "true" ]  # "false" or empty
-  then
-    ln -s "$1" "$2"
-    success "linked $1 to $2"
-  fi
-}
-
-install_dotfiles () {
-  info 'installing dotfiles'
-
-  local overwrite_all=false backup_all=false skip_all=false
-
-  for src in $(find "$ETC_ROOT" -maxdepth 2 -name '*.symlink')
-  do
-      dst=$(find_destination "$src")
-      link_file "$src" "$dst"
-  done
-}
-
-install_dotfiles
+done
 
 echo ''
 echo '  All installed!'
