Update system scripts.

diff --git a/bin.symlink/system-cleanup b/bin.symlink/system-cleanup
--- a/bin.symlink/system-cleanup
+++ b/bin.symlink/system-cleanup
@@ -17,21 +17,22 @@ removes old ones.
 EOF
 
 function info () {
-  printf "  [ \033[00;34m..\033[0m ] $1"
+    echo -e '\033k'$1'\033\\'
+    printf "  [ \033[00;34m..\033[0m ] $1"
 }
 
 function user () {
-  printf "\r  [ \033[0;33m?\033[0m ] $1 "
+    printf "\r  [ \033[0;33m?\033[0m ] $1 "
 }
 
 function success () {
-  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
+    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
 }
 
 function fail () {
-  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
-  echo ''
-  exit 1
+    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
+    echo ''
+    exit 1
 }
 
 function cleanup() {
@@ -55,7 +56,7 @@ function clean-language-runtime() {
 }
 
 function clean-python(){
-   clean-language-runtime "python-updater"
+    clean-language-runtime "python-updater"
 }
 
 function clean-haskell(){
